// File name: b04902023_HW3_NonogramImageConst.h
// Define NonogramImage Constants

// header gaurds
#ifndef B04902023_HW2_NONOGRAMIMAGECONST_H
#define B04902023_HW2_NONOGRAMIMAGECONST_H

enum NonogramImageConst {
    NONOGRAM_IMAGE_CONST_UNDETERMINED =  0,
    NONOGRAM_IMAGE_CONST_SELECTED     = -1,
    NONOGRAM_IMAGE_CONST_UNSELECTED   = -2
};

enum NonogramImageLogicSolveConst {
    NONOGRAM_IMAGE_LOGIC_SOLVE_CONST_UNDETERMINED = 0,
    NONOGRAM_IMAGE_LOGIC_SOLVE_CONST_DONE,
    NONOGRAM_IMAGE_LOGIC_SOLVE_CONST_CONTRADICT
};

enum NonogramImageLogicSolveSingleLineConst {
    NONOGRAM_IMAGE_LOGIC_SOLVE_SINGLE_LINE_CONST_UNDETERMINED = 0,
    NONOGRAM_IMAGE_LOGIC_SOLVE_SINGLE_LINE_CONST_DONE,
    NONOGRAM_IMAGE_LOGIC_SOLVE_SINGLE_LINE_CONST_CONTRADICT
};

enum NonogramImageLogicSolveSingleBrickConst {
    NONOGRAM_IMAGE_LOGIC_SOLVE_SINGLE_BRICK_CONST_UNDETERMINED = 0,
    NONOGRAM_IMAGE_LOGIC_SOLVE_SINGLE_BRICK_CONST_CONTRADICT
};

#endif
